clc;
clear;
close all;

%% ==========================
% AEGISSAT MISSION ANIMATION
%% ==========================

fps = 20;
duration = 25;
N = fps*duration;

figure('Color','k',...
       'Position',[50 50 1400 800]);

for k = 1:N

    clf

    t = k/fps;

    %% ------------------------
    % Mission Phase Logic
    %% ------------------------

    if t < 5

        phase = "ORBIT INSERTION";
        event = "Orbit Insertion Complete";

    elseif t < 10

        phase = "RECON ACTIVE";
        event = "Payload Activated";

    elseif t < 15

        phase = "ECLIPSE";
        event = "Power Conservation Initiated";

    elseif t < 20

        phase = "THERMAL EVENT";
        event = "Emergency Protocol Executed";

    else

        phase = "RECOVERY";
        event = "System Recovery Successful";

    end

    %% ------------------------
    % Earth and Orbit
    %% ------------------------

    subplot(1,1,1)

    hold on

    axis equal
    axis([-8 8 -5 5])

    set(gca,'Color','k')
    set(gca,'XColor','none')
    set(gca,'YColor','none')

    %% Earth

    theta = linspace(0,2*pi,500);

    fill(1.5*cos(theta),...
         1.5*sin(theta),...
         [0 0.4 1],...
         'EdgeColor','none');

    %% Orbit

    orbitR = 3.8;

    plot(orbitR*cos(theta),...
         orbitR*sin(theta),...
         'w--');

    %% Sun

    sunX = 6;
    sunY = 2;

    scatter(sunX,sunY,...
            1500,...
            'y',...
            'filled');

    text(sunX,...
         sunY+0.6,...
         'SUN',...
         'Color','y',...
         'FontSize',12,...
         'FontWeight','bold');

    %% Satellite Motion

    ang = 2*pi*(k/N)*3;

    satX = orbitR*cos(ang);
    satY = orbitR*sin(ang);

    plot(satX,...
         satY,...
         'ws',...
         'MarkerSize',12,...
         'MarkerFaceColor','w');

    text(satX+0.2,...
         satY,...
         'AEGISSAT',...
         'Color','w',...
         'FontSize',10);

    %% Solar Beam

    if t < 15 || t > 20

        plot([sunX satX],...
             [sunY satY],...
             'y',...
             'LineWidth',2);

    end

    %% Eclipse Shadow

    if t>=10 && t<15

        fill([-2.5 -2.5 -6 -6],...
             [-2 2 2 -2],...
             [0.2 0.2 0.2],...
             'FaceAlpha',0.5,...
             'EdgeColor','none');

        text(-5,...
             2.5,...
             'EARTH SHADOW',...
             'Color','w');

    end

    %% Recon Scan Cone

    if t>=5 && t<10

        patch([satX satX-1 satX+1],...
              [satY satY-2 satY-2],...
              'g',...
              'FaceAlpha',0.3);

        text(-6,...
             -4,...
             'Recon Sweep Active',...
             'Color','g',...
             'FontSize',12);

    end

    %% Thermal Event

    if t>=15 && t<20

        scatter(satX,...
                satY,...
                600,...
                'r');

        text(-6,...
             -4,...
             'THERMAL ANOMALY',...
             'Color','r',...
             'FontSize',12,...
             'FontWeight','bold');

    end

    %% Recovery

    if t>=20

        text(-6,...
             -4,...
             'SYSTEM RECOVERY COMPLETE',...
             'Color','g',...
             'FontSize',12,...
             'FontWeight','bold');

    end

    %% ------------------------
    % Mission Information
    %% ------------------------

    text(-7.5,4.3,...
        sprintf('MISSION TIME : %04.1f s',t),...
        'Color','w',...
        'FontSize',14,...
        'FontWeight','bold');

    text(-7.5,3.6,...
        ['PHASE : ' char(phase)],...
        'Color','c',...
        'FontSize',14);

    rectangle('Position',[-7.5 -0.5 4.5 1.4],...
              'EdgeColor','w');

    text(-7.2,0.3,...
        'EVENT LOG',...
        'Color','w',...
        'FontSize',12,...
        'FontWeight','bold');

    text(-7.2,-0.1,...
        event,...
        'Color','w',...
        'FontSize',11);

    %% Title

    title('AEGISSAT : AUTONOMOUS DEFENCE RECONNAISSANCE MISSION',...
          'Color','w',...
          'FontSize',16);

    drawnow

end

%% Final Screen

figure('Color','k');

axis off

text(0.5,0.6,...
    'MISSION SUCCESSFUL',...
    'Color','g',...
    'FontSize',28,...
    'FontWeight','bold',...
    'HorizontalAlignment','center');

text(0.5,0.4,...
    'AEGISSAT',...
    'Color','w',...
    'FontSize',22,...
    'HorizontalAlignment','center');